// Tablas de valores normales de referencia (adulto, salvo indicación).
// { id, grupo, nombre, valor, unidad, nota? }
const REFS = [
// Hemograma
{grupo:"Hemograma", nombre:"Hemoglobina (hombre)", valor:"13.5–17.5", unidad:"g/dL"},
{grupo:"Hemograma", nombre:"Hemoglobina (mujer)", valor:"12.0–15.5", unidad:"g/dL"},
{grupo:"Hemograma", nombre:"Hematocrito (hombre)", valor:"41–53", unidad:"%"},
{grupo:"Hemograma", nombre:"Hematocrito (mujer)", valor:"36–46", unidad:"%"},
{grupo:"Hemograma", nombre:"Leucocitos", valor:"4.500–11.000", unidad:"/µL"},
{grupo:"Hemograma", nombre:"Neutrófilos", valor:"1.800–7.700 (40–75%)", unidad:"/µL"},
{grupo:"Hemograma", nombre:"Linfocitos", valor:"1.000–4.800 (20–45%)", unidad:"/µL"},
{grupo:"Hemograma", nombre:"Monocitos", valor:"200–800 (2–10%)", unidad:"/µL"},
{grupo:"Hemograma", nombre:"Eosinófilos", valor:"0–450 (0–6%)", unidad:"/µL"},
{grupo:"Hemograma", nombre:"Plaquetas", valor:"150.000–450.000", unidad:"/µL"},
{grupo:"Hemograma", nombre:"VCM (volumen corpuscular medio)", valor:"80–100", unidad:"fL"},
{grupo:"Hemograma", nombre:"HCM", valor:"27–33", unidad:"pg"},
{grupo:"Hemograma", nombre:"Reticulocitos", valor:"0.5–2.5", unidad:"%"},
{grupo:"Hemograma", nombre:"VHS (velocidad de sedimentación)", valor:"<20 (H) / <30 (M)", unidad:"mm/h"},
{grupo:"Hemograma", nombre:"PCR (proteína C reactiva)", valor:"<0.5–1.0", unidad:"mg/dL"},
// Coagulación
{grupo:"Coagulación", nombre:"Tiempo de protrombina (TP)", valor:"11–13.5", unidad:"seg"},
{grupo:"Coagulación", nombre:"INR", valor:"0.8–1.2", unidad:""},
{grupo:"Coagulación", nombre:"TTPA", valor:"25–35", unidad:"seg"},
{grupo:"Coagulación", nombre:"Fibrinógeno", valor:"200–400", unidad:"mg/dL"},
{grupo:"Coagulación", nombre:"Dímero D", valor:"<0.5", unidad:"µg/mL FEU"},
// Bioquímica / metabólico
{grupo:"Bioquímica", nombre:"Glucosa (ayuno)", valor:"70–100", unidad:"mg/dL"},
{grupo:"Bioquímica", nombre:"Hemoglobina glicosilada (HbA1c)", valor:"<5.7 (normal) / 5.7–6.4 (prediabetes) / ≥6.5 (diabetes)", unidad:"%"},
{grupo:"Bioquímica", nombre:"Urea", valor:"15–45", unidad:"mg/dL"},
{grupo:"Bioquímica", nombre:"Nitrógeno ureico (BUN)", valor:"7–20", unidad:"mg/dL"},
{grupo:"Bioquímica", nombre:"Creatinina (hombre)", valor:"0.7–1.3", unidad:"mg/dL"},
{grupo:"Bioquímica", nombre:"Creatinina (mujer)", valor:"0.6–1.1", unidad:"mg/dL"},
{grupo:"Bioquímica", nombre:"Ácido úrico", valor:"3.5–7.2 (H) / 2.6–6.0 (M)", unidad:"mg/dL"},
{grupo:"Bioquímica", nombre:"Proteínas totales", valor:"6.0–8.3", unidad:"g/dL"},
{grupo:"Bioquímica", nombre:"Albúmina", valor:"3.5–5.0", unidad:"g/dL"},
// Electrolitos
{grupo:"Electrolitos", nombre:"Sodio", valor:"135–145", unidad:"mEq/L"},
{grupo:"Electrolitos", nombre:"Potasio", valor:"3.5–5.0", unidad:"mEq/L"},
{grupo:"Electrolitos", nombre:"Cloro", valor:"98–107", unidad:"mEq/L"},
{grupo:"Electrolitos", nombre:"Calcio total", valor:"8.5–10.5", unidad:"mg/dL"},
{grupo:"Electrolitos", nombre:"Calcio iónico", valor:"1.15–1.35", unidad:"mmol/L"},
{grupo:"Electrolitos", nombre:"Magnesio", valor:"1.7–2.2", unidad:"mg/dL"},
{grupo:"Electrolitos", nombre:"Fósforo", valor:"2.5–4.5", unidad:"mg/dL"},
{grupo:"Electrolitos", nombre:"Bicarbonato", valor:"22–28", unidad:"mEq/L"},
// Gases arteriales
{grupo:"Gases arteriales", nombre:"pH arterial", valor:"7.35–7.45", unidad:""},
{grupo:"Gases arteriales", nombre:"PaCO₂", valor:"35–45", unidad:"mmHg"},
{grupo:"Gases arteriales", nombre:"PaO₂", valor:"80–100", unidad:"mmHg"},
{grupo:"Gases arteriales", nombre:"HCO₃⁻ (gases)", valor:"22–26", unidad:"mEq/L"},
{grupo:"Gases arteriales", nombre:"Saturación de O₂", valor:"95–100", unidad:"%"},
{grupo:"Gases arteriales", nombre:"Exceso de base (BE)", valor:"-2 a +2", unidad:"mEq/L"},
{grupo:"Gases arteriales", nombre:"Lactato", valor:"0.5–2.0 (normal) / >4 grave", unidad:"mmol/L"},
// Perfil hepático
{grupo:"Perfil hepático", nombre:"ALT/GPT", valor:"7–56", unidad:"U/L"},
{grupo:"Perfil hepático", nombre:"AST/GOT", valor:"10–40", unidad:"U/L"},
{grupo:"Perfil hepático", nombre:"Fosfatasa alcalina", valor:"44–147", unidad:"U/L"},
{grupo:"Perfil hepático", nombre:"GGT", valor:"8–61 (H) / 5–36 (M)", unidad:"U/L"},
{grupo:"Perfil hepático", nombre:"Bilirrubina total", valor:"0.3–1.2", unidad:"mg/dL"},
{grupo:"Perfil hepático", nombre:"Bilirrubina directa", valor:"0.0–0.3", unidad:"mg/dL"},
{grupo:"Perfil hepático", nombre:"Amilasa", valor:"28–100", unidad:"U/L"},
{grupo:"Perfil hepático", nombre:"Lipasa", valor:"10–140", unidad:"U/L"},
// Perfil lipídico
{grupo:"Perfil lipídico", nombre:"Colesterol total", valor:"<200 (deseable)", unidad:"mg/dL"},
{grupo:"Perfil lipídico", nombre:"LDL", valor:"<100 (óptimo)", unidad:"mg/dL"},
{grupo:"Perfil lipídico", nombre:"HDL", valor:">40 (H) / >50 (M)", unidad:"mg/dL"},
{grupo:"Perfil lipídico", nombre:"Triglicéridos", valor:"<150", unidad:"mg/dL"},
// Función tiroidea
{grupo:"Función tiroidea", nombre:"TSH", valor:"0.4–4.0", unidad:"mUI/L"},
{grupo:"Función tiroidea", nombre:"T4 libre", valor:"0.8–1.8", unidad:"ng/dL"},
{grupo:"Función tiroidea", nombre:"T3 libre", valor:"2.3–4.2", unidad:"pg/mL"},
// Cardíaco
{grupo:"Marcadores cardíacos", nombre:"Troponina I", valor:"<0.04 (varía por ensayo, usar percentil 99 local)", unidad:"ng/mL"},
{grupo:"Marcadores cardíacos", nombre:"CK total", valor:"30–200", unidad:"U/L"},
{grupo:"Marcadores cardíacos", nombre:"CK-MB", valor:"0–25", unidad:"U/L"},
{grupo:"Marcadores cardíacos", nombre:"NT-proBNP", valor:"<125 (<75 años) / <450 (≥75 años)", unidad:"pg/mL"},
// LDH y otros
{grupo:"Otros analitos", nombre:"Lactato deshidrogenasa (LDH)", valor:"140–280", unidad:"U/L"},
{grupo:"Otros analitos", nombre:"Alfafetoproteína (adulto)", valor:"<10", unidad:"ng/mL"},
{grupo:"Otros analitos", nombre:"Ferritina (hombre)", valor:"30–400", unidad:"ng/mL"},
{grupo:"Otros analitos", nombre:"Ferritina (mujer)", valor:"15–150", unidad:"ng/mL"},
{grupo:"Otros analitos", nombre:"Hierro sérico", valor:"60–170", unidad:"µg/dL"},
{grupo:"Otros analitos", nombre:"Vitamina B12", valor:"200–900", unidad:"pg/mL"},
{grupo:"Otros analitos", nombre:"Ácido fólico", valor:"2.7–17.0", unidad:"ng/mL"},
// Niveles terapéuticos de fármacos
{grupo:"Niveles terapéuticos de fármacos", nombre:"Digoxina", valor:"0.8–2.0 (tóxico >2.5)", unidad:"ng/mL"},
{grupo:"Niveles terapéuticos de fármacos", nombre:"Litio", valor:"0.6–1.2 (tóxico >1.5)", unidad:"mEq/L"},
{grupo:"Niveles terapéuticos de fármacos", nombre:"Ácido valproico", valor:"50–100", unidad:"µg/mL"},
{grupo:"Niveles terapéuticos de fármacos", nombre:"Carbamazepina", valor:"4–12", unidad:"µg/mL"},
{grupo:"Niveles terapéuticos de fármacos", nombre:"Fenitoína", valor:"10–20", unidad:"µg/mL"},
{grupo:"Niveles terapéuticos de fármacos", nombre:"Fenobarbital", valor:"15–40", unidad:"µg/mL"},
{grupo:"Niveles terapéuticos de fármacos", nombre:"Vancomicina (valle)", valor:"10–20 (según objetivo AUC/MIC)", unidad:"µg/mL"},
{grupo:"Niveles terapéuticos de fármacos", nombre:"Gentamicina (valle)", valor:"<2", unidad:"µg/mL"},
{grupo:"Niveles terapéuticos de fármacos", nombre:"Teofilina", valor:"10–20", unidad:"µg/mL"},
{grupo:"Niveles terapéuticos de fármacos", nombre:"Amikacina (valle)", valor:"<5–10", unidad:"µg/mL"},
// G6PD
{grupo:"Fármacos a evitar en déficit de G6PD", nombre:"Riesgo alto — evitar", valor:"Dapsona, primaquina, rasburicasa, azul de metileno, nitrofurantoína", unidad:""},
{grupo:"Fármacos a evitar en déficit de G6PD", nombre:"Riesgo moderado — precaución", valor:"Sulfametoxazol/trimetoprim, cloroquina, ácido nalidíxico, vitamina K (altas dosis)", unidad:""},
{grupo:"Fármacos a evitar en déficit de G6PD", nombre:"Riesgo bajo — generalmente seguros", valor:"Paracetamol, ácido acetilsalicílico (dosis bajas), cloranfenicol", unidad:""},
// Requerimiento proteico
{grupo:"Requerimiento de proteínas por edad", nombre:"Lactante 0–6 meses", valor:"1.52", unidad:"g/kg/día"},
{grupo:"Requerimiento de proteínas por edad", nombre:"Niño 1–3 años", valor:"1.05", unidad:"g/kg/día"},
{grupo:"Requerimiento de proteínas por edad", nombre:"Niño 4–13 años", valor:"0.95", unidad:"g/kg/día"},
{grupo:"Requerimiento de proteínas por edad", nombre:"Adolescente 14–18 años", valor:"0.85", unidad:"g/kg/día"},
{grupo:"Requerimiento de proteínas por edad", nombre:"Adulto sano", valor:"0.8", unidad:"g/kg/día"},
{grupo:"Requerimiento de proteínas por edad", nombre:"Adulto crítico/hipercatabólico", valor:"1.2–2.0", unidad:"g/kg/día"},
// TFG / KDIGO
{grupo:"Categorías KDIGO de eGFR", nombre:"G1 — Normal o alta", valor:"≥90", unidad:"mL/min/1.73m²"},
{grupo:"Categorías KDIGO de eGFR", nombre:"G2 — Levemente disminuida", valor:"60–89", unidad:"mL/min/1.73m²"},
{grupo:"Categorías KDIGO de eGFR", nombre:"G3a — Leve a moderadamente disminuida", valor:"45–59", unidad:"mL/min/1.73m²"},
{grupo:"Categorías KDIGO de eGFR", nombre:"G3b — Moderada a severamente disminuida", valor:"30–44", unidad:"mL/min/1.73m²"},
{grupo:"Categorías KDIGO de eGFR", nombre:"G4 — Severamente disminuida", valor:"15–29", unidad:"mL/min/1.73m²"},
{grupo:"Categorías KDIGO de eGFR", nombre:"G5 — Falla renal", valor:"<15", unidad:"mL/min/1.73m²"},
// Orina
{grupo:"Orina completa", nombre:"Densidad urinaria", valor:"1.005–1.030", unidad:""},
{grupo:"Orina completa", nombre:"pH urinario", valor:"4.5–8.0", unidad:""},
{grupo:"Orina completa", nombre:"Proteinuria (cuali)", valor:"Negativa / trazas", unidad:""},
{grupo:"Orina completa", nombre:"Microalbuminuria", valor:"<30", unidad:"mg/g creatinina"},
{grupo:"Orina completa", nombre:"Leucocitos en orina", valor:"0–5", unidad:"/campo"},
{grupo:"Orina completa", nombre:"Eritrocitos en orina", valor:"0–2", unidad:"/campo"},
// LCR
{grupo:"Líquido cefalorraquídeo", nombre:"Presión de apertura", valor:"10–20 (adulto en decúbito)", unidad:"cmH₂O"},
{grupo:"Líquido cefalorraquídeo", nombre:"Leucocitos LCR", valor:"0–5", unidad:"/µL"},
{grupo:"Líquido cefalorraquídeo", nombre:"Proteínas LCR", valor:"15–45", unidad:"mg/dL"},
{grupo:"Líquido cefalorraquídeo", nombre:"Glucosa LCR", valor:"50–80 (≈2/3 de la glucemia)", unidad:"mg/dL"},
// Signos vitales
{grupo:"Signos vitales (adulto)", nombre:"Frecuencia cardíaca", valor:"60–100", unidad:"lpm"},
{grupo:"Signos vitales (adulto)", nombre:"Frecuencia respiratoria", valor:"12–20", unidad:"rpm"},
{grupo:"Signos vitales (adulto)", nombre:"PA sistólica", valor:"90–120", unidad:"mmHg"},
{grupo:"Signos vitales (adulto)", nombre:"PA diastólica", valor:"60–80", unidad:"mmHg"},
{grupo:"Signos vitales (adulto)", nombre:"Temperatura axilar", valor:"36.0–37.0", unidad:"°C"},
{grupo:"Signos vitales (adulto)", nombre:"Saturación de O₂", valor:"95–100", unidad:"%"},
// Pediatría (referencial, varía mucho con la edad)
{grupo:"Signos vitales (pediatría)", nombre:"FC recién nacido", valor:"100–180", unidad:"lpm"},
{grupo:"Signos vitales (pediatría)", nombre:"FC lactante (1–12 m)", valor:"100–160", unidad:"lpm"},
{grupo:"Signos vitales (pediatría)", nombre:"FC preescolar (1–5 a)", valor:"90–140", unidad:"lpm"},
{grupo:"Signos vitales (pediatría)", nombre:"FC escolar (6–12 a)", valor:"70–120", unidad:"lpm"},
{grupo:"Signos vitales (pediatría)", nombre:"FR recién nacido", valor:"30–60", unidad:"rpm"},
{grupo:"Signos vitales (pediatría)", nombre:"FR lactante", valor:"25–40", unidad:"rpm"},
{grupo:"Signos vitales (pediatría)", nombre:"FR escolar", valor:"18–25", unidad:"rpm"},
];

if (typeof module !== "undefined") module.exports = { REFS };
